### ISSUE TITLE
CREATE command escapes directory separator

### ISSUE THREAD

**Issue by SquircleSpace** [ProtonMail/proton-bridge#227]
When I attempt to issue a CREATE command to make a new folder (in this case, `Folders/rss/xkcd`), the folder that is actually created contains backslashes that seem to be escaping the directory separators in my folder name.  Please see the following log snippet.

```
time="Oct 26 19:32:48.441" level=debug msg="000003 CREATE Folders/rss/xkcd" loc="127.0.0.1:1143" pkg=imap/client rem="127.0.0.1:59932"
time="Oct 26 19:32:48.441" level=debug msg="Creating mailbox" name=Folders/rss/xkcd pkg=store
<snip>
time="Oct 26 19:32:53.300" level=debug msg="* LIST (\\Noinferiors) \"/\" \"Folders/rss\\\\/xkcd\"" loc="127.0.0.1:1143" pkg=imap/server rem="127.0.0.1:59920"
```

The CREATE command names the folder `Folders/rss/xkcd`, but the folder the backend produces is actually named `Folders/rss\/xkcd`.  The web UI represents this as a folder that contains a literal `/` character.

![image](https://user-images.githubusercontent.com/2561504/138991556-a023a5d2-50c7-4b30-910c-0f21b6733649.png)

## Expected Behavior
When a CREATE command is issued, the directory separator character should be respected.

## Current Behavior
When a CREATE command is issued, the directory separator character is seemingly escaped by the backend.  As a result, the created folder isn't properly nested in the folder hierarchy.

## Steps to Reproduce

1. Issue a CREATE command for a folder.  Ensure that at least two levels of the folder hierarchy do not already exist.
2. Issue a LIST command and/or look at the web UI.
3. Observe that the created folder's hierarchy wasn't preserved

## Version Information
ProtonMail Bridge version 1.6.9+git on NixOS with Nixpkgs revision e85f0175e3effe9ba191d66c09e8f1b7d6362d5e

## Context (Environment)
I'm writing a program that, as part of its function, wants to create new folder hierarchies in my ProtonMail account.

For what its worth, the issue reproduces with Kmail as well.  Creating a nested folder in Kmail produces the exact same result as with my program.  That is, the ProtonMail backend seems to discard the hierarchy information by inserting escaping backslash characters.

## Detailed Description

See above

**Comment by exander77** [comment]
Seems to me, that Bridge is not yet prepared for features that were moved from beta (nested folders). Instead of creating nested folders, it creates folders including slash.
```
CREATE Folders/Test\\\\/Test
```
Should create a folder:
```
LIST () "/" "Folders/Test\\\\/Test"
```
```
CREATE Folders/Test/Test
```
Should create a nested folder:
```
LIST () "/" "Folders/Test/TestNested"
```

**Comment by andrzejsza** [comment]
yes, the above is correct. this is by current design but needs to change. for internal reference: GODT-620

**Comment by sawft99** [comment]
Just noticed something similar as well. I'm not issuing direct commands, but in Thunderbird I can see that it was changed to backslashes and made a nested folder each time with the name being the word after the slash.

A folder labeled: 

Name1/Name2/Name3

recursively becomes:

Name1\
     Name2\
          Name3

Wish this minor bug would be fixed after almost 6 months

**Comment by dsommers** [comment]
This is still an issue with Proton Mail Bridge 2.3.0.

**Comment by andrzejsza** [comment]
but should be fixed with 3.x. could you please try the latest beta and confirm?

**Comment by dsommers** [comment]
This works with the v3 releases via Thunderbird.  I've created subfolders where it is located in the right spot with the right name.

Removing the folder from Thunderbird also removes the folder in the Proton Mail webmail as expected.
Removing the folder from Proton Mail (webmail) does make the folder inaccessible in the mail client, but it is still present there - where it can't be opened and can't be unsubscribed.  Deleting it in Thunderbird works.

These simple tests was done with an empty folder, similar tests should probably be done with folders containing mails.

**Comment by andrzejsza** [comment]
tested the behavior and it works as expected. for some clients, they need to be restarted but from the correctness point of view there is nothing else here to do.
