### ISSUE TITLE
Vault gets wiped on startup when using pass

### ISSUE THREAD

**Issue by beauby** [ProtonMail/proton-bridge#470]
Using `pass` on Linux, the vault gets wiped when starting proton-bridge (`bridge -c`) if the gpg key is not unlocked (the key has a passphrase):

```
WARN[Mar 28 17:05:26.856] Failed to get test credentials from keychain  error="exit status 2: gpg: public key decryption failed: No such file or directory\ngpg: decryption failed: No such file or directory\n" helper="*pass.Pass"
WARN[Mar 28 17:05:26.948] Failed to load existing vault, vault has been reset  error="failed to decrypt vault: cipher: message authentication failed"
WARN[Mar 28 17:05:26.953] The vault is corrupt and has been wiped      
```

## Expected Behavior
Gracefully fail, or prompt to unlock.

## Current Behavior
Wipe out the vault.

## Steps to Reproduce
1. Set up `pass` with passphrase-protected gpg key
2. Run `bridge -c`

## Version Information
3.10.0

**Comment by zwets** [comment]
A big +1 on this issue. It has happened a few times that I either dismissed the GPG password dialog box or waited to long to fill it in (apparently there is a timeout).

What happens then is that I lose _everything_ and need to set up bridge all over again: settings, accounts, client-side passwords, followed by the long and costly re-download of my whole mailbox.

I would be very happy if this were fixed!

**Comment by deiKruve** [comment]
I use thefollowing sequence on Debian:

>pass xxx

This will ask for the passphrase and give the key. It opens the database. The database seems to stay open for a limited time.
Thereafter I can start bridge without a problem.

>protonmail-bridge --cli

j.

**Comment by JonathanReeve** [comment]
This is a big problem, since whenever the vault gets wiped, I have to do this: 

1. Check the CLI for a new password
2. Edit the password in `pass` with the new password, for IMAP
3. Do the same for SMTP
4. Export the new `cert.pem` key
5. Move the key to the location where my mail agent (isync/mbsync) is configured to find it
6. Wait for a large sync operation to sync all my mail over again
7. Trash my whole maildir folder, since the UID validity has now changed, and `mbsync` won't sync any more 
8. Recreate the maildir

**Comment by Always-Self-Hosted** [comment]
It looks like this is still an issue, and even if you don't set a password for your gpg key. I know my example is trying to run proton-bridge headless in a docker container, but regardless the issue is the same. Despite mounting volumes to persist the required files, even in the same container just restarting the process results in the vault being recreated and the imap/smtp passwords changing. Which I would of assumed the pass database would still be open? 

```
FROM golang:1.21.9 as build
ARG PROTON_BRIDGE_VERSION
RUN apt-get update && apt-get install -y libsecret-1-dev
RUN git clone https://github.com/ProtonMail/proton-bridge.git
WORKDIR proton-bridge
RUN git checkout tags/v$PROTON_BRIDGE_VERSION
RUN make build-nogui
FROM debian:12.8-slim
COPY --from=build /go/proton-bridge /opt/proton-bridge
ENV PATH="$PATH:/opt/proton-bridge"
RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
    gnupg \
    pass \
    libsecret-1-dev \
    && rm -rf /var/lib/apt/lists/*
RUN gpg --batch --passphrase "" --quick-gen-key "proton-bridge" default default never
RUN pass init "proton-bridge"
EXPOSE 1025
EXPOSE 1143
CMD ( echo "login"; echo $PROTON_EMAIL; echo $PROTON_PASSWORD; sleep 15s; echo "info 0"; echo "exit" ) | proton-bridge --cli && proton-bridge --noninteractive
```
```
2025-01-12 10:18:12.151872+00:00[33mWARN[0m[Jan 12 10:18:12.151] Failed to add test credentials to keychain    [33merror[0m="failed to open dbus connection: exec: \"dbus-launch\": executable file not found in $PATH" [33mhelper[0m="*keychain.SecretServiceDBusHelper"
2025-01-12 10:18:12.413630+00:00[33mWARN[0m[Jan 12 10:18:12.413] no vault key found, generating new            [33merror[0m="could not get keychain item: credentials not found in native keychain"
2025-01-12 10:18:13.676839+00:00[33mWARN[0m[Jan 12 10:18:13.676] Failed to load existing vault, vault has been reset  [33merror[0m="failed to decrypt vault: cipher: message authentication failed"
2025-01-12 10:18:13.690527+00:00[33mWARN[0m[Jan 12 10:18:13.690] The vault is corrupt and has been wiped
```
